from playwright.sync_api import sync_playwright, TimeoutError as PWTimeoutError
import sys
import json
import urllib.request
import urllib.error

BASE_URL = "http://localhost:4200"
API_URL = "http://localhost:5000/api"
USERNAME = "admin"
PASSWORD = "Admin123!"


def fail(msg: str) -> None:
    print(f"SMOKE_FAIL: {msg}")
    sys.exit(1)


def http_json(method: str, url: str, body: dict | None = None, token: str | None = None) -> dict:
    data = None if body is None else json.dumps(body).encode("utf-8")
    req = urllib.request.Request(url, method=method)
    req.add_header("Content-Type", "application/json")
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    try:
        with urllib.request.urlopen(req, data=data, timeout=30) as resp:
            raw = resp.read().decode("utf-8")
            return json.loads(raw) if raw else {}
    except urllib.error.HTTPError as ex:
        payload = ex.read().decode("utf-8", errors="ignore")
        raise RuntimeError(f"HTTP {ex.code} at {url}: {payload}") from ex


def ensure_box_id(token: str) -> int:
    boxes_resp = http_json("GET", f"{API_URL}/boxes", token=token)
    boxes = boxes_resp.get("data") or []
    if boxes:
        return int(boxes[0]["boxId"])

    create_payload = {
        "name": "Smoke Box",
        "description": "Autogenerated for smoke test",
        "cronExpression": "*/15 * * * *",
        "timeZoneId": "Etc/UTC",
        "initialTask": {
            "name": "Smoke Task",
            "description": "Autogenerated",
            "command": "cmd /c echo smoke",
            "taskType": "Exe"
        }
    }
    created = http_json("POST", f"{API_URL}/boxes", body=create_payload, token=token)
    box = created.get("data") or {}
    if "boxId" not in box:
        raise RuntimeError("Could not create smoke box")
    return int(box["boxId"])


auth_resp = http_json("POST", f"{API_URL}/auth/login", body={"username": USERNAME, "password": PASSWORD})
token = (auth_resp.get("data") or {}).get("accessToken")
if not token:
    fail("Unable to authenticate against API with admin credentials")

box_id = ensure_box_id(token)


with sync_playwright() as p:
    browser = p.chromium.launch(headless=True)
    page = browser.new_page(viewport={"width": 1440, "height": 900})

    try:
        page.goto(BASE_URL, wait_until="networkidle", timeout=60000)

        # Login
        page.fill("input[formcontrolname='username']", USERNAME)
        page.fill("input[formcontrolname='password']", PASSWORD)
        page.click("button[type='submit']")
        page.wait_for_load_state("networkidle", timeout=60000)

        # 1) Failed tasks detail contains task type and command, and Retry action is absent
        page.click("a:has-text('Failed Tasks')")
        page.wait_for_url("**/failed", timeout=15000)
        page.wait_for_selector("text=Execution Failures", timeout=15000)
        retry_actions = page.locator("table.data-table button:has-text('Retry'), table.data-table a:has-text('Retry')")
        if retry_actions.count() > 0:
            fail("Retry action still present in Failed Tasks page")

        row_count = page.locator("table.data-table tbody tr").count()
        if row_count > 0:
            page.locator("table.data-table tbody tr").first.click(force=True)
            try:
                page.wait_for_selector(".modal-overlay .detail-table", timeout=8000)
                modal_text = page.locator(".modal-overlay .modal-body").inner_text().lower()
                if "task type" not in modal_text or "command" not in modal_text:
                    fail("Failed Tasks detail modal is missing Task Type/Command fields")
            except PWTimeoutError:
                print("SMOKE_WARN: Failed row exists but detail modal did not open; Task Type/Command check skipped")
        else:
            print("SMOKE_WARN: No failed task rows available to validate modal fields")

        if page.locator(".modal-overlay").count() > 0:
            close_button = page.locator(".modal-overlay button:has-text('Close')").first
            if close_button.count() > 0:
                close_button.click()
                page.wait_for_timeout(300)

        # 2) Box detail inline edit flow + 3) basic responsiveness
        page.click("a:has-text('Boxes')")
        page.wait_for_url("**/boxes", timeout=15000)
        page.wait_for_selector("table.data-table tbody tr", timeout=15000)

        view_button = page.locator("button:has-text('View')").first
        if view_button.count() == 0:
            fail("No View button found in boxes list")

        view_button.click()
        page.wait_for_load_state("networkidle", timeout=60000)
        page.wait_for_selector("text=Execution Outlook", timeout=15000)

        edit_button = page.locator("button:has-text('Edit')").first
        if edit_button.count() == 0:
            fail("Edit button not found in box detail")

        edit_button.click()
        page.wait_for_selector("text=Edit Box", timeout=10000)
        page.locator(".modal-overlay .modal-footer button:has-text('Cancel')").first.click()
        page.wait_for_selector("text=Edit Box", state="hidden", timeout=10000)

        # If modal closes, title should be gone
        if page.locator("text=Edit Box").count() > 0:
            fail("Inline Edit Box modal did not close correctly")

        print("SMOKE_OK: UI smoke checks passed")
    finally:
        page.screenshot(path="smoke_ui_result.png", full_page=True)
        browser.close()
