import { Injectable, PLATFORM_ID, computed, inject, signal } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';

export type AppLanguage = 'en' | 'es';
export type TranslationParams = Record<string, string | number | boolean | null | undefined>;

const LANGUAGE_KEY = 'CHRONIQ_language';
const SUPPORTED_LANGUAGES: AppLanguage[] = ['en', 'es'];

const ES_TRANSLATIONS: Record<string, string> = {
  'Account': 'Cuenta',
  'Account Center': 'Centro de cuenta',
  'Active': 'Activo',
  'Active Boxes': 'Boxes activos',
  'Add': 'Agregar',
  'Add User': 'Agregar usuario',
  'Actions': 'Acciones',
  'Active BoxRun Queue': 'Cola activa de BoxRun',
  'All': 'Todo',
  'Admin': 'Administrador',
  'Admins': 'Administradores',
  'All timestamps are normalized to {timeZone} for this session.': 'Todas las marcas de tiempo se normalizan a {timeZone} para esta sesion.',
  'API Offline': 'API sin conexion',
  'API Status': 'Estado de API',
  'Application Errors': 'Errores de aplicacion',
  'Application Log': 'Log de aplicacion',
  'Back': 'Volver',
  'Back to executions': 'Volver a ejecuciones',
  'Back to boxes': 'Volver a boxes',
  'Back to {name}': 'Volver a {name}',
  'Box': 'Box',
  'Box Detail': 'Detalle del box',
  'Box Name': 'Nombre del box',
  'BoxRun ID': 'ID de BoxRun',
  'Boxes': 'Boxes',
  'Boxes And Tasks': 'Boxes y tareas',
  'Cancel': 'Cancelar',
  'Confirm': 'Confirmar',
  'Are you sure?': 'Estas seguro?',
  'Change Password': 'Cambiar contrasena',
  'Close': 'Cerrar',
  'Confirm Delete': 'Confirmar eliminacion',
  'Confirm New Password': 'Confirmar nueva contrasena',
  'Control Panel': 'Panel de control',
  'Current Password': 'Contrasena actual',
  'Current password is required.': 'La contrasena actual es obligatoria.',
  'Config': 'Configurar',
  'Connection, authentication and sender identity.': 'Conexion, autenticacion e identidad del remitente.',
  'Delivery': 'Entrega',
  'Enable SMTP failure notifications': 'Habilitar notificaciones SMTP de fallo',
  'Enter a valid email address for the test send.': 'Ingresa un correo valido para el envio de prueba.',
  'Failure alert delivery for scheduled tasks.': 'Entrega de alertas de fallo para tareas programadas.',
  'From Address': 'Direccion remitente',
  'From Display Name': 'Nombre del remitente',
  'Host': 'Host',
  'Host is required when notifications are enabled.': 'El host es obligatorio cuando las notificaciones estan habilitadas.',
  'Leave blank to keep the saved password.': 'Deja en blanco para conservar la contrasena guardada.',
  'Loading SMTP settings...': 'Cargando configuracion SMTP...',
  'Port': 'Puerto',
  'Port must be between 1 and 65535.': 'El puerto debe estar entre 1 y 65535.',
  'Recipient': 'Destinatario',
  'Reload': 'Recargar',
  'Run Controls': 'Controles de ejecucion',
  'Sender': 'Remitente',
  'SMTP Notifications': 'Notificaciones SMTP',
  'Test Email': 'Correo de prueba',
  'Use TLS / SSL': 'Usar TLS / SSL',
  'Uses the saved backend configuration.': 'Usa la configuracion guardada del backend.',
  'A valid sender address is required when notifications are enabled.': 'Se requiere una direccion de remitente valida cuando las notificaciones estan habilitadas.',
  'Authentication': 'Autenticacion',
  'Created': 'Creado',
  'Clear': 'Limpiar',
  'Command is required.': 'El comando es obligatorio.',
  'Context': 'Contexto',
  'Days of the Week': 'Dias de la semana',
  'Department controls governance defaults for this box.': 'El departamento controla los valores de gobernanza para este box.',
  'Enter at least 2 characters.': 'Ingresa al menos 2 caracteres.',
  'Every box must have at least one task. Configure the first one below.': 'Cada box debe tener al menos una tarea. Configura la primera abajo.',
  'Every Hour': 'Cada hora',
  'Every 10 min': 'Cada 10 min',
  'Every 15 min': 'Cada 15 min',
  'Every 30 min': 'Cada 30 min',
  'First Task': 'Primera tarea',
  'Frequency': 'Frecuencia',
  'Global Search': 'Busqueda global',
  'Ignore dependencies': 'Ignorar dependencias',
  'Last Run': 'Ultima ejecucion',
  'Limit': 'Limite',
  'Name is required.': 'El nombre es obligatorio.',
  'Not assigned': 'Sin asignar',
  'Once Daily at:': 'Una vez al dia a las:',
  'Open Box': 'Abrir box',
  'Open Task': 'Abrir tarea',
  'Only active tasks in this box are available.': 'Solo estan disponibles las tareas activas de este box.',
  'Parent box': 'Box padre',
  'Preview:': 'Vista previa:',
  'Queue Box': 'Encolar box',
  'Schedule': 'Programacion',
  'Scope': 'Alcance',
  'Search boxes and tasks from a single entry point, then jump directly to the matching record. Use Ctrl+K or / to focus the search box.': 'Busca boxes y tareas desde una sola entrada y salta directamente al registro correspondiente. Usa Ctrl+K o / para enfocar la busqueda.',
  'Search text': 'Texto de busqueda',
  'Task name is required.': 'El nombre de la tarea es obligatorio.',
  'Tasks': 'Tareas',
  'This schedule will run in:': 'Esta programacion se ejecutara en:',
  'Time Zone': 'Zona horaria',
  'Time zone is required.': 'La zona horaria es obligatoria.',
  'Type': 'Tipo',
  'Use valid emails separated by comma (max 10).': 'Usa correos validos separados por coma (maximo 10).',
  '(required)': '(obligatorio)',
  'Dashboard': 'Panel',
  'DB Connected': 'BD conectada',
  'DB Disconnected': 'BD desconectada',
  'DB Status': 'Estado de BD',
  'Database is disconnected. DB-backed sections may be empty until connectivity returns.': 'La base de datos esta desconectada. Las secciones respaldadas por BD pueden estar vacias hasta que vuelva la conectividad.',
  'Database, worker pool, and API self-check results.': 'Resultados de autoverificacion de base de datos, pool de workers y API.',
  'Check': 'Verificacion',
  'Correlation Id': 'Id de correlacion',
  'Error': 'Error',
  'Error File': 'Archivo de error',
  'Error Line': 'Linea de error',
  'Error Method': 'Metodo de error',
  'Exception': 'Excepcion',
  'Exception Type': 'Tipo de excepcion',
  'Exit Code': 'Codigo de salida',
  'Failed Executions': 'Ejecuciones fallidas',
  'Loading health dashboard...': 'Cargando panel de salud...',
  'Log File': 'Archivo de log',
  'No application warnings or errors found in the selected window.': 'No se encontraron advertencias ni errores de aplicacion en la ventana seleccionada.',
  'No failed task executions found in the selected window.': 'No se encontraron ejecuciones fallidas en la ventana seleccionada.',
  'Operational failures and interrupted task executions.': 'Fallas operativas y ejecuciones de tareas interrumpidas.',
  'Queue Depth': 'Profundidad de cola',
  'Readiness Checks': 'Verificaciones de preparacion',
  'Request Path': 'Ruta de solicitud',
  'Source': 'Origen',
  'Startup Recovery': 'Recuperacion de arranque',
  'Stale Executions': 'Ejecuciones obsoletas',
  'Status Code': 'Codigo de estado',
  'Stop or resume the current workflow when the run state allows it.': 'Deten o reanuda el flujo actual cuando el estado de la ejecucion lo permita.',
  'Time': 'Hora',
  'Warnings, errors, and fatal records stored in ApplicationLogs.': 'Advertencias, errores y registros fatales almacenados en ApplicationLogs.',
  'Worker Utilization': 'Uso de workers',
  'Delete': 'Eliminar',
  'Delete Task': 'Eliminar tarea',
  'Delete task {name}?': 'Eliminar la tarea {name}?',
  'Deleting...': 'Eliminando...',
  'Dependencies': 'Dependencias',
  'Detailed operational view with task breakdown, logs and aggregate metrics.': 'Vista operativa detallada con desglose de tareas, logs y metricas agregadas.',
  'Department Management': 'Gestion de departamentos',
  'Department Registry': 'Registro de departamentos',
  'Departments': 'Departamentos',
  'Description': 'Descripcion',
  'Contact Email': 'Correo de contacto',
  'Contact email is required and must be valid.': 'El correo de contacto es obligatorio y debe ser valido.',
  'Edit Department': 'Editar departamento',
  'Log Retention': 'Retencion de logs',
  'Loading departments...': 'Cargando departamentos...',
  'Must be at least 1 day.': 'Debe ser al menos 1 dia.',
  'Name is required and must be at least 3 characters.': 'El nombre es obligatorio y debe tener al menos 3 caracteres.',
  'New Department': 'Nuevo departamento',
  'Ownership contact and retention defaults.': 'Contacto responsable y valores predeterminados de retencion.',
  'Update ownership contact and retention defaults.': 'Actualiza contacto responsable y valores predeterminados de retencion.',
  'Details': 'Detalles',
  'Error Message': 'Mensaje de error',
  'Duration': 'Duracion',
  'Edit': 'Editar',
  'Email': 'Correo',
  'Enabled': 'Habilitado',
  'End': 'Fin',
  'End Time': 'Hora de fin',
  'Ended': 'Finalizo',
  'English': 'Ingles',
  'Enter': 'Entrar',
  'Execution Control': 'Control de ejecuciones',
  'Execution Detail': 'Detalle de ejecucion',
  'Execution Metrics': 'Metricas de ejecucion',
  'Execution progress': 'Progreso de ejecucion',
  'Execution Orchestration Hub': 'Centro de orquestacion de ejecuciones',
  'Executions': 'Ejecuciones',
  'Pending': 'Pendiente',
  'Running': 'En ejecucion',
  'Stopping': 'Deteniendo',
  'Success': 'Exito',
  'Completed': 'Completado',
  'Failed': 'Fallido',
  'Cancelled': 'Cancelado',
  'Partial': 'Parcial',
  'Aborted': 'Abortado',
  'Skipped': 'Omitido',
  'NotExecuted': 'No ejecutado',
  'Dismiss': 'Descartar',
  'Failed Today': 'Fallidas hoy',
  'Force Start': 'Iniciar forzado',
  'Force Start Task': 'Iniciar tarea forzada',
  'Failed tasks will be re-executed. Are you sure you want to resume this workflow?': 'Las tareas fallidas se volveran a ejecutar. Estas seguro de reanudar este flujo?',
  'Health': 'Salud',
  'Hide Details': 'Ocultar detalles',
  'Language': 'Idioma',
  'Language / Idioma': 'Idioma / Language',
  'Latest execution records available for inspection from the dashboard.': 'Ultimos registros de ejecucion disponibles para revisar desde el panel.',
  'Latest execution outcome per task within this BoxRun.': 'Ultimo resultado de ejecucion por tarea dentro de este BoxRun.',
  'Loading...': 'Cargando...',
  'Loading BoxRun details...': 'Cargando detalles de BoxRun...',
  'Loading executions...': 'Cargando ejecuciones...',
  'Loading logs...': 'Cargando logs...',
  'Loading users...': 'Cargando usuarios...',
  'Login': 'Inicio de sesion',
  'Logout': 'Cerrar sesion',
  'Main Dashboard': 'Panel principal',
  'Main Menu': 'Menu principal',
  'Menu Principal': 'Menu principal',
  'Name': 'Nombre',
  'New Password': 'Nueva contrasena',
  'New password and confirmation do not match.': 'La nueva contrasena y la confirmacion no coinciden.',
  'New password is required.': 'La nueva contrasena es obligatoria.',
  'New password must be at least 8 characters.': 'La nueva contrasena debe tener al menos 8 caracteres.',
  'New password must include at least one letter and one number.': 'La nueva contrasena debe incluir al menos una letra y un numero.',
  'No': 'No',
  'No executions recorded yet.': 'Aun no hay ejecuciones registradas.',
  'No active executions. All workflows completed successfully.': 'No hay ejecuciones activas. Todos los flujos terminaron correctamente.',
  'No description configured for this box.': 'No hay descripcion configurada para este box.',
  'Individual task view with execution history, KPIs and management actions.': 'Vista individual de tarea con historial de ejecucion, KPIs y acciones de administracion.',
  'Loading box details...': 'Cargando detalles del box...',
  'Loading task details...': 'Cargando detalles de tarea...',
  'Avg Duration': 'Duracion promedio',
  'Started At': 'Inicio',
  'Last Execution Status': 'Ultimo estado de ejecucion',
  'Edit Box': 'Editar box',
  'Save Box': 'Guardar box',
  'Delete Box': 'Eliminar box',
  'Add Task': 'Agregar tarea',
  'Edit Task': 'Editar tarea',
  'This action cannot be undone.': 'Esta accion no se puede deshacer.',
  'No logs found for this execution.': 'No se encontraron logs para esta ejecucion.',
  'None': 'Ninguna',
  'Operator': 'Operador',
  'Orchestrate your workflows with Chroniq.': 'Orquesta tus flujos de trabajo con Chroniq.',
  'Password': 'Contrasena',
  'Password is required.': 'La contrasena es obligatoria.',
  'Password updated successfully.': 'Contrasena actualizada correctamente.',
  'Passwords do not match.': 'Las contrasenas no coinciden.',
  'Progress': 'Progreso',
  'Recent Task Executions': 'Ejecuciones recientes de tareas',
  'Recovery: --': 'Recuperacion: --',
  'Recovery: Disabled': 'Recuperacion: deshabilitada',
  'Recovery: Pending': 'Recuperacion: pendiente',
  'Registered Boxes': 'Boxes registrados',
  'Reason': 'Motivo',
  'Reason is required.': 'El motivo es obligatorio.',
  'Requested By': 'Solicitado por',
  'Refresh': 'Actualizar',
  'Resumable': 'Reanudables',
  'Resumable failed runs. Shows the latest failed job per box and excludes fully completed workflows.': 'Ejecuciones fallidas reanudables. Muestra el ultimo trabajo fallido por box y excluye flujos completados por completo.',
  'Resume': 'Reanudar',
  'Resume BoxRun': 'Reanudar BoxRun',
  'Role': 'Rol',
  'Rows': 'Filas',
  '{count} rows': '{count} filas',
  'Running Now': 'En ejecucion',
  'Save': 'Guardar',
  'Save Task': 'Guardar tarea',
  'Saving...': 'Guardando...',
  'Settings': 'Configuracion',
  'Show Details': 'Mostrar detalles',
  'Show newest first': 'Mostrar mas recientes primero',
  'Show oldest first': 'Mostrar mas antiguos primero',
  'Sign In': 'Iniciar sesion',
  'SMTP Notification Settings': 'Configuracion de notificaciones SMTP',
  'Spanish': 'Espanol',
  'Scheduled For': 'Programado para',
  'Start': 'Inicio',
  'Start Time': 'Hora de inicio',
  'Stop Current Run': 'Detener ejecucion actual',
  'Stop Run': 'Detener ejecucion',
  'Stop requested. Running tasks may continue until they finish, but no new pending tasks will be scheduled.': 'Detencion solicitada. Las tareas en ejecucion pueden continuar hasta terminar, pero no se programaran nuevas tareas pendientes.',
  'Started': 'Inicio',
  'Starting...': 'Iniciando...',
  'Status': 'Estado',
  'Succeeded Today': 'Exitosas hoy',
  'System Health': 'Salud del sistema',
  'System Online': 'Sistema en linea',
  'Task': 'Tarea',
  'Task Detail': 'Detalle de tarea',
  'Task Error Details': 'Detalles del error de tarea',
  'Task Executions': 'Ejecuciones de tareas',
  'Task Logs': 'Logs de tarea',
  'Task Name': 'Nombre de tarea',
  'Task execution logs': 'Logs de ejecucion de tarea',
  'Timestamp': 'Marca de tiempo',
  'Level': 'Nivel',
  'Message': 'Mensaje',
  'Stack Trace': 'Traza',
  '(No error message)': '(Sin mensaje de error)',
  '(No stack trace available)': '(Sin traza disponible)',
  'This will execute {name} ignoring its dependencies. Continue?': 'Esto ejecutara {name} ignorando sus dependencias. Continuar?',
  'This will stop scheduling remaining tasks for this run. Tasks already running will be allowed to finish. Do you want to continue?': 'Esto detendra la programacion de tareas restantes para esta ejecucion. Las tareas que ya estan corriendo podran terminar. Deseas continuar?',
  'Total Duration': 'Duracion total',
  'Total Tasks': 'Total de tareas',
  'Trigger': 'Disparador',
  'Unable to change password.': 'No se pudo cambiar la contrasena.',
  'Unable to load execution history. Check API connection.': 'No se pudo cargar el historial de ejecucion. Revisa la conexion con la API.',
  'Unknown user': 'Usuario desconocido',
  'User Administration': 'Administracion de usuarios',
  'User Directory': 'Directorio de usuarios',
  'Username': 'Usuario',
  'Username is required.': 'El usuario es obligatorio.',
  'Users': 'Usuarios',
  'Validating...': 'Validando...',
  'Viewer': 'Lector',
  'View Details': 'Ver detalles',
  'View Error': 'Ver error',
  'View Logs': 'Ver logs',
  'Visible Runs': 'Ejecuciones visibles',
  'Yes': 'Si',
  '{active}/{total} Workers': '{active}/{total} trabajadores',
  '{count} exec': '{count} ejec.',
  '{count} in queue': '{count} en cola',
  '{count} runs': '{count} ejecuciones',
  '{count} stale > {minutes}m': '{count} obsoletas > {minutes}m',
  '-- Workers': '-- trabajadores',
  '-- in queue': '-- en cola',
  '-- stale': '-- obsoletas',
  'Just now': 'Ahora mismo',
  'Never synced': 'Nunca sincronizado',
  '{seconds}s ago': 'hace {seconds}s',
  'Recovery: {execCount} exec / {runCount} runs @ {time}': 'Recuperacion: {execCount} ejec. / {runCount} corridas @ {time}',
  'Invalid credentials. Check username and password.': 'Credenciales invalidas. Verifica usuario y contrasena.',
  'Username hint': 'Tu nombre de usuario',
  'Password hint': 'Ingresa tu contrasena'
};

const TRANSLATIONS: Record<AppLanguage, Record<string, string>> = {
  en: {},
  es: ES_TRANSLATIONS
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  private readonly platformId = inject(PLATFORM_ID);
  private readonly isBrowser = isPlatformBrowser(this.platformId);
  private readonly _language = signal<AppLanguage>(this.detectInitialLanguage());

  readonly language = this._language.asReadonly();
  readonly languageName = computed(() => this.t(this._language() === 'es' ? 'Spanish' : 'English'));

  setLanguage(language: AppLanguage): void {
    const next = this.normalizeLanguage(language);
    this._language.set(next);
    if (this.isBrowser) {
      localStorage.setItem(LANGUAGE_KEY, next);
      document.documentElement.lang = next;
    }
  }

  t(key: string, params: TranslationParams = {}): string {
    const template = TRANSLATIONS[this._language()][key] ?? key;
    return template.replace(/\{(\w+)\}/g, (_, param: string) => String(params[param] ?? ''));
  }

  private detectInitialLanguage(): AppLanguage {
    if (!this.isBrowser) return 'en';

    const stored = localStorage.getItem(LANGUAGE_KEY);
    if (stored) {
      const normalized = this.normalizeLanguage(stored);
      document.documentElement.lang = normalized;
      return normalized;
    }

    const systemLanguage = navigator.languages?.[0] ?? navigator.language;
    const normalized = this.normalizeLanguage(systemLanguage);
    document.documentElement.lang = normalized;
    return normalized;
  }

  private normalizeLanguage(language: string): AppLanguage {
    const normalized = language.toLowerCase().split('-')[0] as AppLanguage;
    return SUPPORTED_LANGUAGES.includes(normalized) ? normalized : 'en';
  }
}
